name: METviewer_py3.6.3
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6.3
  - python-dateutil
  - python-libarchive-c
  - pandas=0.25.0
  - numpy=1.17.0
  - scipy=1.3.1
  - yaml=0.1.7=
  - plotly=4.9.0
  - python-kaleido
  - psutil
  - requests
  - scipy
  - matplotlib
  - lxml
  - pymysql
  - bootstrapped