name: METviewer_py3.6.3
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6.3
  - python-dateutil
  - python-libarchive-c
  - pandas
  - numpy=1.17.0
  - scipy=1.3.1
  - yaml=0.1.7
  - python-kaleido
  - psutil
  - requests
  - matplotlib
  - lxml
  - pymysql
  - bootstrapped
  - retrying
  - plotly=4.9
  - statsmodels
  - netCDF4
  - pingouin